title: Collin McDevitt
description: Academic website of Collin McDevitt.
url: "https://cmcdev-code.github.io"
baseurl: ""
markdown: kramdown
permalink: pretty

kramdown:
  input: GFM
  hard_wrap: false
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - assets/icons
  - assets/pics
